"""Adding category,puplished

Revision ID: 66a9584e3419
Revises: 
Create Date: 2021-03-18 21:12:19.004927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a9584e3419'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.add_column('posts', sa.Column('category', sa.String(length=120), nullable=True))
    op.add_column('posts', sa.Column('published', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('slug', sa.String(length=240), nullable=True))
    op.create_unique_constraint(None, 'posts', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'slug')
    op.drop_column('posts', 'published')
    op.drop_column('posts', 'category')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('create_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
